name: money_bank
description: Money Bank Flutter App (Wallet + MLM + Chat + Admin)

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  http: ^0.13.5
  provider: ^6.0.5
  shared_preferences: ^2.0.17
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.1
  cloud_firestore: ^4.2.0
  firebase_messaging: ^14.2.1
  flutter_local_notifications: ^12.0.4
  intl: ^0.17.0
  url_launcher: ^6.1.7
  flutter_svg: ^1.1.6
  image_picker: ^0.8.6
  file_picker: ^5.2.4
  socket_io_client: ^2.0.0-beta.4
  fluttertoast: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/rupee_icon.png
