workflows:
  flutter-workflow:
    name: Flutter Workflow for Money Bank App
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          cd frontend
          flutter pub get
      - name: Recreate android & ios folders
        script: |
          cd frontend
          rm -rf android ios
          flutter create -t app .
      - name: Run tests
        script: |
          cd frontend
          flutter test
      - name: Build APK
        script: |
          cd frontend
          flutter build apk --release
    artifacts:
      - frontend/build/app/outputs/flutter-apk/app-release.apk
